---

- name: "F5 NODE ADD YT EXAMPLE"
  hosts: Star_Wars_F5
  connection: local
  gather_facts: false
#  collections:
#   - f5networks.f5_modules

  tasks:
    - name: "CREATE NODE"
      f5networks.f5_modules.bigip_node:
        host: 10.2.0.4
        name: Test_Ansible_Node_From_Git
        provider:
          validate_certs: no
          server: 192.168.0.122
          user: root
          password: 
 
